services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_ENDPOINT: ${API_ENDPOINT}
        NEXT_PUBLIC_API_ENDPOINT: ${NEXT_PUBLIC_API_ENDPOINT}
        NEXT_PUBLIC_IMAGE_DOMAIN: ${NEXT_PUBLIC_IMAGE_DOMAIN}
    expose:
      - "3000"
    environment:
      - API_ENDPOINT=${API_ENDPOINT}
      - NEXT_PUBLIC_API_ENDPOINT=${NEXT_PUBLIC_API_ENDPOINT}
      - NEXT_PUBLIC_IMAGE_DOMAIN=${NEXT_PUBLIC_IMAGE_DOMAIN}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
